class Movie {
  const Movie({
    required this.id,
    required this.title,
    required this.genre,
    required this.type,
    required this.year,
    required this.runtimeMinutes,
    required this.posterAsset,
    required this.description,
    required this.rating,
    required this.ratingCount,
    required this.tags,
  });

  final int id;
  final String title;
  final String genre;
  final String type;
  final int year;
  final int runtimeMinutes;
  final String posterAsset;
  final String description;
  final double rating;
  final int ratingCount;
  final List<String> tags;
}

const movies = [
  Movie(
    id: 1,
    title: '별빛 아래 우리',
    genre: '로맨스',
    type: '드라마',
    year: 2024,
    runtimeMinutes: 120,
    posterAsset: 'assets/images/posters/hero_under_the_starlight.jpg',
    description: "바쁜 현대 사회 속에서 서로의 존재를 잊고 살아가던 두 남녀가 우연한 계기로 작은 천문대에서 만나게 됩니다. 매일 밤 별을 관측하며 서로의 상처를 치유하고, 잊고 있던 꿈과 사랑을 다시금 깨닫게 되는 따뜻한 이야기입니다. 과거의 아픔으로 인해 사람에게 마음을 열지 못하던 여주인공은, 별자리처럼 변함없는 모습으로 자신을 기다려주는 남주인공을 통해 서서히 마음의 문을 열게 됩니다. 하지만 두 사람 앞에 놓인 현실적인 장벽들은 그들의 관계를 시험하게 되는데... 별이 쏟아지는 밤하늘 아래, 그들이 나눈 조용한 약속들은 과연 영원할 수 있을까요? 눈부신 영상미와 감성적인 OST가 어우러져 깊은 여운을 남기는 올 겨울 최고의 로맨스 영화.",
    rating: 4.5,
    ratingCount: 1245,
    tags: ['로맨스', '드라마', '감동적인'],
  ),
  Movie(
    id: 2,
    title: '우주의 끝에서',
    genre: 'SF',
    type: '영화',
    year: 2024,
    runtimeMinutes: 108,
    posterAsset: 'assets/images/posters/poster_abyss_walker.jpg',
    description: '인류 마지막 탐사선이 우주의 끝에서 발견한 것은 예상치 못한 진실이었다.',
    rating: 4.1,
    ratingCount: 532,
    tags: ['SF', '액션', '스릴있는'],
  ),
  Movie(
    id: 3,
    title: '공허의 메아리',
    genre: 'SF',
    type: '영화',
    year: 2023,
    runtimeMinutes: 134,
    posterAsset: 'assets/images/posters/poster_echoes_of_the_void.jpg',
    description: '신호가 끊긴 우주 정거장에서 깨어난 생존자는, 자신을 부르는 목소리의 정체를 쫓다 우주의 가장 깊은 비밀과 마주한다.',
    rating: 4.3,
    ratingCount: 889,
    tags: ['SF', '미스터리', '긴장감'],
  ),
  Movie(
    id: 4,
    title: '네 번째 오후',
    genre: '드라마',
    type: '영화',
    year: 2022,
    runtimeMinutes: 112,
    posterAsset: 'assets/images/posters/poster_fourth_afternoon.jpg',
    description: '매주 같은 카페에서 마주치는 네 사람의 오후. 사소한 대화 속에서 각자의 상처와 희망이 천천히 드러난다.',
    rating: 4.0,
    ratingCount: 421,
    tags: ['드라마', '잔잔한', '힐링'],
  ),
  Movie(
    id: 5,
    title: '밤의 그림자',
    genre: '스릴러',
    type: '영화',
    year: 2024,
    runtimeMinutes: 118,
    posterAsset: 'assets/images/posters/poster_night_shadows.jpg',
    description: '연쇄 실종 사건을 쫓는 형사가 자신의 과거와 얽힌 진실에 다가갈수록, 도시의 밤은 더 깊은 어둠을 드러낸다.',
    rating: 4.4,
    ratingCount: 1532,
    tags: ['스릴러', '범죄', '긴장감'],
  ),
  Movie(
    id: 6,
    title: '속삭이는 숲',
    genre: '공포',
    type: '영화',
    year: 2023,
    runtimeMinutes: 96,
    posterAsset: 'assets/images/posters/poster_whispering_woods.jpg',
    description: '봉인된 숲으로 캠핑을 떠난 청년들. 밤이 되자 나무 사이에서 들려오는 속삭임이 그들을 하나씩 집어삼킨다.',
    rating: 3.8,
    ratingCount: 674,
    tags: ['공포', '미스터리', '오싹한'],
  ),
  Movie(
    id: 7,
    title: '웃음의 조건',
    genre: '코미디',
    type: '영화',
    year: 2024,
    runtimeMinutes: 101,
    posterAsset: 'assets/images/posters/poster_fourth_afternoon.jpg',
    description: '망해가는 극단을 살리기 위해 뭉친 괴짜 배우들이 벌이는 좌충우돌 무대 뒤 소동극.',
    rating: 4.2,
    ratingCount: 998,
    tags: ['코미디', '유쾌한', '감동적인'],
  ),
  Movie(
    id: 8,
    title: '마지막 질주',
    genre: '액션',
    type: '영화',
    year: 2024,
    runtimeMinutes: 127,
    posterAsset: 'assets/images/posters/poster_abyss_walker.jpg',
    description: '은퇴를 앞둔 전설의 드라이버가 마지막 레이스에 모든 것을 건다. 트랙 위에서 펼쳐지는 숨 막히는 추격전.',
    rating: 4.5,
    ratingCount: 2043,
    tags: ['액션', '스릴있는', '짜릿한'],
  ),
  Movie(
    id: 9,
    title: '별빛 아래 다시',
    genre: '로맨스',
    type: '드라마',
    year: 2023,
    runtimeMinutes: 115,
    posterAsset: 'assets/images/posters/hero_under_the_starlight.jpg',
    description: '헤어진 연인이 10년 만에 같은 천문대에서 재회한다. 바뀐 것과 바뀌지 않은 것 사이에서 두 사람은 다시 마음을 확인한다.',
    rating: 4.3,
    ratingCount: 1120,
    tags: ['로맨스', '감동적인', '재회'],
  ),
  Movie(
    id: 10,
    title: '시간의 틈',
    genre: 'SF',
    type: '영화',
    year: 2022,
    runtimeMinutes: 141,
    posterAsset: 'assets/images/posters/poster_echoes_of_the_void.jpg',
    description: '시간을 되돌리는 실험에 성공한 물리학자가, 매번 달라지는 결과 속에서 지켜야 할 단 하나의 순간을 찾아 나선다.',
    rating: 4.1,
    ratingCount: 765,
    tags: ['SF', '드라마', '여운있는'],
  ),
  Movie(
    id: 11,
    title: '그림자 수사대',
    genre: '스릴러',
    type: '드라마',
    year: 2024,
    runtimeMinutes: 110,
    posterAsset: 'assets/images/posters/poster_night_shadows.jpg',
    description: '베일에 싸인 특수 수사팀이 권력의 최상층부를 겨눈다. 진실에 가까워질수록 그들을 노리는 손길도 거세진다.',
    rating: 4.0,
    ratingCount: 540,
    tags: ['스릴러', '범죄', '반전'],
  ),
  Movie(
    id: 12,
    title: '숲속의 비밀',
    genre: '판타지',
    type: '영화',
    year: 2023,
    runtimeMinutes: 105,
    posterAsset: 'assets/images/posters/poster_whispering_woods.jpg',
    description: '평범한 소녀가 숲 깊은 곳에서 말하는 동물들의 왕국을 발견하고, 사라진 봄을 되찾기 위한 모험을 떠난다.',
    rating: 4.4,
    ratingCount: 1310,
    tags: ['판타지', '모험', '따뜻한'],
  ),
  Movie(
    id: 13,
    title: '오후 세 시의 편지',
    genre: '드라마',
    type: '영화',
    year: 2021,
    runtimeMinutes: 98,
    posterAsset: 'assets/images/posters/poster_fourth_afternoon.jpg',
    description: '세상을 떠난 어머니가 남긴 편지를 따라 작은 바닷마을을 찾은 딸이, 몰랐던 어머니의 청춘과 마주한다.',
    rating: 4.6,
    ratingCount: 1877,
    tags: ['드라마', '감동적인', '가족'],
  ),
  Movie(
    id: 14,
    title: '폭주 기관차',
    genre: '액션',
    type: '영화',
    year: 2022,
    runtimeMinutes: 119,
    posterAsset: 'assets/images/posters/poster_abyss_walker.jpg',
    description: '브레이크가 고장 난 채 폭주하는 열차. 승객을 구하기 위해 한 정비공이 목숨을 건 사투를 벌인다.',
    rating: 3.9,
    ratingCount: 612,
    tags: ['액션', '재난', '긴장감'],
  ),
  Movie(
    id: 15,
    title: '마지막 상영관',
    genre: '코미디',
    type: '드라마',
    year: 2023,
    runtimeMinutes: 107,
    posterAsset: 'assets/images/posters/hero_under_the_starlight.jpg',
    description: '폐관을 앞둔 동네 극장을 지키려는 사장과 단골손님들이 벌이는 따뜻하고 엉뚱한 마지막 축제.',
    rating: 4.2,
    ratingCount: 833,
    tags: ['코미디', '힐링', '감동적인'],
  ),
  Movie(
    id: 16,
    title: '한밤의 저택',
    genre: '공포',
    type: '영화',
    year: 2024,
    runtimeMinutes: 94,
    posterAsset: 'assets/images/posters/poster_night_shadows.jpg',
    description: '하룻밤만 머물면 거액을 주겠다는 제안. 낡은 저택에 모인 사람들은 곧 이 집이 그들을 내보낼 생각이 없음을 깨닫는다.',
    rating: 3.7,
    ratingCount: 489,
    tags: ['공포', '미스터리', '오싹한'],
  ),
];

Movie? findMovieById(int? id) {
  for (final movie in movies) {
    if (movie.id == id) return movie;
  }
  return null;
}
